### ISSUE TITLE
live reload

### ISSUE THREAD

**Issue by wanghaisheng** [windvalley/apior#1]
一般会在conf目录下起一个叫     'nginx-app.conf' 然后.conf 里面include一下
我们这个是要直接在nginx.conf的location这里配app目录下的应用逻辑嘛

我的核心诉求是这个脚手架配docker 我改了配置和app里的代码能热更新 方便调试

**Comment by windvalley** [comment]
应用的路由和业务逻辑不在nginx.conf中配置, 除非增加执行阶段, 目前nginx.conf默认配置有rewrite、access、content三个执行阶段;
路由在`app/router.lua`中配置, 应用的业务逻辑在`app/apis/`目录中编写, 一个接口可以写一个lua文件, 每个文件可以包含openresty不同的执行阶段, 可以参考下`app/apis/app1/example_api1.lua`这个示例文件.

如果是修改nginx.conf配置的话, 还是需要reload才能生效的;
如果是修改应用的lua代码, 想要实现全局lua代码变化后热更新, 需要在nginx.conf中增加指令`lua_code_cache off`, 在调试的场景下可以这么做, 不过对于一些特殊的调试场景也不能使用这个指令, 比如对模块级别变量的测试, 如果关闭lua_code_cache将测试不出正确的结果; 
还可以在lua业务代码中通过loadstring或者loadfile做具体lua文件(模块)的热更新,  不过这个需要在业务代码中去实现了, 而且不是全局lua代码变化后的热更新.

**Comment by windvalley** [comment]
@wanghaisheng hello, 该项目已经通过其他方式实现了热更新, 当`*.conf`或`*.lua`文件有变化时会自动reload openresty, 欢迎使用 , 您也可以将本项目`nginx.conf`中实现该功能的Lua代码粘贴到您的openresty项目中来使用这个功能:)

**Comment by wanghaisheng** [comment]
ok
