### ISSUE TITLE
docker scripts and doc

### ISSUE THREAD

**Issue by wanghaisheng** [windvalley/apior#2]
or官方镜像  doc里面写一下就可以了

**Comment by wanghaisheng** [comment]
docker run --rm -it  \
           -p 8891:80  \
           -v "${PWD}:/usr/local/openresty/nginx/use-openresty"  \
           -v "${PWD}/conf:/etc/nginx/conf.d "  \
           openresty/openresty:alpine

这样子好像也不行

**Comment by windvalley** [comment]
```bash
docker run --rm --name use-openresty \
    -v ~/github/use-openresty:/app \
    -p 8891:80 \
    -d openresty/openresty:alpine \
    /usr/local/openresty/bin/openresty -p /app -c conf/nginx.conf -g "daemon off;"
```
