### ISSUE TITLE
bs app开发

### ISSUE THREAD

**Issue by wanghaisheng** [windvalley/apior#3]
有么有可能整合https://github.com/williamwen1986/Luakit

我们公司业务目前前端有基于安卓的app和基于pc的vue 我们现在这个脚手架有没有可能整合上面这种 做成一个one fit all的starter kit

**Comment by windvalley** [comment]
简单看了下Luakit项目, 如果没看错, 这个应该是用来统一写前端逻辑的, 和OpenResty是不同种类的东西;

OpenResty用来写后端数据或逻辑接口, 供前端调用, 前端无论是手机app还是浏览器等等, 是什么都可以.
